global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api-service"
    static_configs:
      - targets: ["api-service:8000"]
    metrics_path: /metrics

  - job_name: "predictive-autoscaler"
    static_configs:
      - targets: ["autoscaler:9091"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
